### ISSUE TITLE
does not save progress in ChM tier when switching modules

### ISSUE THREAD

**Issue by rileykeen** [iq-eq-us/dot-io#14]
need to more broadly define when a session ends so that progress will never be lost

![ChM_save_when](https://user-images.githubusercontent.com/64341447/226000185-bd192799-f90f-42ca-9082-d4991ec4c079.gif)

**Comment by jdestgermain** [comment]
I think this should be a high priority issue, if it isn't already. 
![image](https://user-images.githubusercontent.com/11359044/229110552-e2ebcd86-ec34-4560-bf66-281d7b3b910c.png)

While this is maybe somewhat true "progress tracking works on the 'all chords' tier" it doesn't actually seem like it does? I mean, during your session it seems to but it seems to be dropping the progress if you move anywhere else. And even then, when you come back, it doesn't seem to be picking back up where you were in the chords and is starting you over (at least for me).

Like this user, I am excited to use iq eq more (even as a more experienced user!), but I can't in good heart use it right now (or recommend it) because it is not saving progress, which is a key for the training platforms effectiveness.

**Comment by rileykeen** [comment]
Thanks for sharing. This is definitely high priority. I am testing it right now on the beta link. Others can try it here: https://agreeable-bush-04fa3b710.2.azurestaticapps.net/#/

**Comment by jdestgermain** [comment]
I think this one is fixed now in the main deployed version of the app and the issue can probably be closed.
